### DISCUSSION TITLE
A workflow example without deprecation warnings

### DISCUSSION THREAD

**Discussion by YDX-2147483647** [best-of-lists/best-of#186] [Show and tell]
As discussed in #155, days passed and things get deprecated…

## Example workflow

https://github.com/YDX-2147483647/best-of-bits/blob/b67b4d2000f65a7af3f358cc40c89426b98d807c/.github/workflows/update-best-of-list.yml

```yaml
# Based on https://github.com/best-of-lists/best-of-update-action/blob/v0.8.5/workflows/update-best-of-list.yml
name: update-best-of-list

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to use for this update"
        required: false
  schedule:
    - cron: "0 1 * * 4"

env:
  BRANCH_PREFIX: "update/"

jobs:
  update-best-of-list:
    runs-on: ubuntu-latest
    steps:
      - name: Set version from input
        if: ${{ github.event.inputs != null  &&  github.event.inputs.version != null }}
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
      - name: Set version via date
        if: ${{ ! (env.VERSION != null && env.VERSION != '') }}
        run: echo "VERSION=$(date '+%Y.%m.%d')" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Append time to version if necessary
        shell: bash
        run: |
          git fetch --tags --force
          git show-ref --tags --verify --quiet -- "refs/tags/${{ env.VERSION }}" && echo "VERSION=$(date '+%Y.%m.%d-%H.%M')" >> $GITHUB_ENV || exit 0
      - name: Install best-of generator
        run: pip install best-of==0.8.5
      - name: Update best-of list
        run: >-
          best-of generate projects.yaml
          --libraries-key=${{ secrets.LIBRARIES_KEY }}
          --github-key=${{ secrets.GITHUB_TOKEN }}
          --gitee-key=${{ secrets.GITEE_API_KEY }}
      - name: Report latest changes
        run: |
          echo "# Best-of update: ${{ env.VERSION  }}" >> "$GITHUB_STEP_SUMMARY"
          cat latest-changes.md >> "$GITHUB_STEP_SUMMARY"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: ${{ env.BRANCH_PREFIX }}${{ env.VERSION  }}
          committer: best-of update <actions@github.com>
          commit-message: Update best-of list for version ${{ env.VERSION  }}
          title: "Best-of update: ${{ env.VERSION  }}"
          body: |
            To finish this update: Select `Merge pull request` below and `Confirm merge`.
            Also, make sure to publish the created draft release in the [releases section](../releases) as well.
      - name: Switch to updated branch
        # “Create pull request” committed to a new branch without switching to it,
        # but “Publish release” needs the updated file.
        run: git switch "${{ env.BRANCH_PREFIX }}${{ env.VERSION  }}"
      - name: Publish release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION  }}
          name: "Update: ${{ env.VERSION  }}"
          body_path: "latest-changes.md"
          draft: true
          prerelease: false
```

## Features

- **No deprecation warnings**

  Fix the following warnings.

  - The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, peterjgrainger/action-create-branch@v2.0.1, actions/create-release@v1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
  - The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

  Remove/replace the following dependencies.

  - https://github.com/peterjgrainger/action-create-branch, https://github.com/stefanzweifel/git-auto-commit-action, and [hub](https://hub.github.com)

    Replaced with a single step https://github.com/peter-evans/create-pull-request.

  - https://github.com/actions/create-release

    This repo was archived on Mar 4, 2021, so I replaced it with https://github.com/softprops/action-gh-release.

- **Easier to extend**

  This workflow does not use https://github.com/marketplace/actions/best-of-update-action (which is approximately [a simple `pip install`](https://github.com/best-of-lists/best-of-update-action/blob/d5ab4adb7f28d3776ec355276b5c68ff836e9d24/Dockerfile)).

  If you extend best-of-generator, you can use it directly by [installing from VCS](https://packaging.python.org/en/latest/tutorials/installing-packages/#installing-from-vcs). For example, you can change `run: pip install best-of==0.8.5` to `run: pip install git+https://github.com/mkdocs/best-of-generator`.

- **Job summary**

  The workflow not only saves latest changes to release notes and `*.md`, but also shows it in the job summary.

  This makes debugging less painful.
